---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: {{ .Values.namespace }}
data:
  APP_NAME: "{{ .Values.app.backend.name | default "NODE_EXPRESS" }}"
  APP_ENV: "{{ .Values.app.backend.env | default "local" }}"
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: backend-secret
  namespace: {{ .Values.namespace }}
data:
  APP_KEY: "{{ .Values.app.key | default "secretkey" | b64enc }}"
  DB_HOST: "{{ .Values.db.host | default "localhost" | b64enc }}"
  DB_NAME: "{{ .Values.db.database | default "db_name" | b64enc }}"
  DB_USER: "{{ .Values.db.username | default "db_user" | b64enc }}"
  DB_PASS: "{{ .Values.db.password | default "db_password" | b64enc }}"
  DB_DIALECT: "{{ .Values.db.dialect | default "db_dialect" | b64enc }}"
