---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
  namespace: {{ .Values.namespace }}
data:
  APP_NAME: "{{ .Values.app.frontend.name | default "ANGULAR" }}"
  APP_ENV: "{{ .Values.app.frontend.env | default "local" }}"
  APP_API: "{{ .Values.app.frontend.api | default "localhost:8080" }}"
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: frontend-secret
  namespace: {{ .Values.namespace }}
data:
  APP_KEY: "{{ .Values.app.key | default "secretkey" | b64enc }}"
