apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvcName }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  {{ if default .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.storage.requests | default "1Gi" }}
